services:
  fileflows:
    image: revenz/fileflows
    container_name: fileflows
    restart: unless-stopped
    ports:
      - "19200:5000"
    environment:
      - TempPathHost=/mnt/erb/tmp/fileflow
      - TZ=Asia/Jakarta
      - PUID=1000
      - PGID=100
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/erb/tmp/fileflow:/temp
      - /srv/fileflows/data:/app/Data
      - /srv/fileflows/logs:/app/Logs
      - /mnt/erb/Videos:/media/erb/Videos
      - /mnt/cc/Videos:/media/cc/Videos
    networks:
      - frontend
    # labels:
    #   - sablier.enable=true
    #   - sablier.group=fileflows

networks:
  frontend:
    external: true
