services:
  tugtainer:
    container_name: tugtainer
    image: quenary/tugtainer:latest
    volumes:
      - /srv/tugtainer:/tugtainer
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    networks:
      - frontend
    ports:
      - '9412:80'
  
  # tugtainer-agent:
  # agent:
  #   container_name: tugtainer-agent
  #   image: quenary/tugtainer-agent:latest
  #   volumes:
  #     # You can uncomment this to mount socket directly,
  #     # and remove socket-proxy service and DOCKER_HOST variable
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #   restart: unless-stopped
  #   environment:
  #     # The list of available variables is in env.example
  #     AGENT_SECRET: sangatsecretsekali
  #     # DOCKER_HOST: tcp://socket-proxy:2375
  #   read_only: true
  #   tmpfs:
  #     - /run
  #   networks:
  #     - frontend
  #   ports:
  #     - '9413:8001'
  #   labels:
  #     dev.quenary.tugtainer.protected: True
networks:
  frontend:
    external: true