services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    ports:
      - "8000:8000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/portainer:/data
    networks:
      - frontend
    dns:
      - 10.1.1.200
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1024M
      restart_policy:
        condition: on-failure

networks:
  frontend:
    external: true