services:
  dockhand:
    image: fnsys/dockhand:latest
    container_name: dockhand
    restart: unless-stopped
    #ports:
    #  - 3000:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./dockhand:/app/data
      - /home/el/docker-compose-blueprints:/app/data/docker-compose
    networks:
      - frontend

networks:
  frontend:
    external: true